Iter15
NikitaBarysh/metrics_and_alertinc pull request #15
Opened 2023-11-08 21:18 UTC by NikitaBarysh

2023-11-16 15:35 UTC, Perederey requested changes
В целом отличная работа получилось!
Надо только немного навести порядок

2023-11-16 15:35 UTC, Perederey commented on cmd/agent/main.go
>  	"os/signal"
возьми в привычку делать goimport для сортировки зависимостей

2023-11-16 15:35 UTC, Perederey commented on cmd/agent/main.go
круто было бы добавить еще вылет по ошибки из приложения, если это необходимо, но можно и так

2023-11-16 15:35 UTC, Perederey commented on cmd/server/main.go
> +	}
тут можешь попробовать сделать options pattern https://medium.com/@perederei/mastering-golang-how-to-optimize-your-code-with-option-functions-pattern-for-better-performance-29bc6f5585f0

2023-11-16 15:35 UTC, Perederey commented on cmd/server/main.go
>  	"os"
добавь сортировку импортов

2023-11-16 15:35 UTC, Perederey commented on config/agent/config.go
> +	flag.Int64Var(&cfg.Limit, "l", 8, "rate limit")
отлично, что сделать через Var 👍

2023-11-16 15:35 UTC, Perederey commented on config/agent/config.go
> +	}
по-факту ту нет смысла делать проверку на if тут

default значение для `string` = ``

то есть если у тебя `key != ""`, то все равно `cfg.Key = ""`

Можно упростить :)

2023-11-16 15:35 UTC, Perederey commented on config/agent/config.go
> +	}
тут можно оставить, так как по-умолчанию у тебя стоит 8

2023-11-16 15:35 UTC, Perederey commented on config/server/config.go
> +	if key, exist := os.LookupEnv("KEY"); exist {
exist -> ok

принятро прсто задавать переменную `ok`

2023-11-16 15:35 UTC, Perederey commented on internal/handlers/handlers_test.go
>  package handlers
хотелось бы, чтобы тест осилил 👍

2023-11-16 15:35 UTC, Perederey commented on internal/service/collect_metrics.go
> +	m.storage.UpdateGaugeMetric("FreeMemory", float64(psutilMem.Free))
а что если Total или Free не будет cast в float64? Надо бы сделать проверку, в реальности такие ошибки часто случаются в realtime

2023-11-16 15:35 UTC, Perederey commented on internal/service/hasher/hasher.go
> +var Sign *Hasher
а зачем тебе тут pointer?

2023-11-16 15:35 UTC, Perederey commented on internal/service/hasher/hasher.go
> +}
давай init tests

2023-11-16 15:35 UTC, Perederey commented on internal/service/hasher/middleware.go
> +	})
большая вложенность получается, сделай так, чтобы было наоборот - позитивный кейс за скобками, негативный внутри

плюс PrintLn можно заменить на log

2023-11-16 15:35 UTC, Perederey commented on internal/service/scheduler.go
> +	wg.Add(int(workers))
может тогда workers передавать как int?
А в целом worker может быть частью MetricAction структруры, также как reportInterval, fagRunAddr - так как ты же их не собираешься постоянно менять?

2023-11-17 06:17 UTC, NikitaBarysh commented on internal/service/hasher/hasher.go
> +var Sign *Hasher
Так проще передавать в middleware

2023-11-17 06:18 UTC, NikitaBarysh commented on internal/service/hasher/hasher.go
> +}
Сделать тест на этот метод ?

2023-11-17 17:36 UTC, Perederey commented on internal/service/hasher/hasher.go
> +}
Ага

2023-11-17 20:11 UTC, merged